[package]
name = "etternabot"
version = "0.0.69"
authors = ["James Guess <jamesguessis@gmail.com>", "kangalioo <jannik.a.schaper@web.de>"]
edition = "2018"

[dependencies]
image = "0.23"
serenity = "0.8"
regex = "1.3"
etternaonline_api = { path = "../eo-api" }