[package]
name = "etternabot"
version = "0.0.69"
authors = ["James Guess <jamesguessis@gmail.com>", "kangalioo <jannik.a.schaper@web.de>"]
edition = "2018"

[dependencies]
log = "*"
image = "0.23"

[dependencies.tokio]
version = "0.2.21"
features = ["full"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.reqwest]
version = "0.10"
features = ["json", "blocking"]

[dependencies.sfsdb]
git = "https://github.com/simvux/sfsdb.git"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity.git"
branch = "current"
version = "0.8"
