[package]
name = "eo2"
version = "0.1.0"
edition = "2021"

[dependencies]
etterna = "0.1.0"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.204", features = ["derive"] }
